variables:
  DISABLE_TAGGER: 1
  PUSH_TO_PRODUCTION_REGISTRY: 1
  DOCKERFILE_PATH: Dockerfile

include:
  - project: social-tech/infrastructure/gitlab-templates
    file: /entrypoints/only-build.yaml
